import React from "react";
import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import "./globals.scss";
import TanstackProvider from "./_providers/TanstackProvider";
import { AuthProvider } from "./_contexts/AuthContext";

const tajwal = Tajawal({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className={tajwal.className}>
        <TanstackProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
